### ISSUE TITLE
text in the wrong place

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#49]
Hi Ruslan, 

Happy new year, i hope you have entered 2015 well :)

We have a problem on the InfraHouse website, both in Danish and English. 

Some of the sites have some text in the bottom of the page, which i did not write, and i cannot delete it either!!??
It says which language the site is in, and i have seen it before, but i though it was only me who could see it, since i am able to edit the page - but now a colleague told me that he saw it as well. 

It is on all the pages, is it possible to remove it? it does not look very professional. 

![skaermbillede 2015-01-05 kl 08 57 17](https://cloud.githubusercontent.com/assets/8081414/5610556/aefc34e6-94b9-11e4-8d14-319dd7ac6355.png)
![skaermbillede 2015-01-05 kl 08 56 53](https://cloud.githubusercontent.com/assets/8081414/5610564/b3e1ce9e-94b9-11e4-8b1d-b22adbc58408.png)

**Comment by mamont77** [comment]
Happy new year ))
Let me check.

**Comment by mamont77** [comment]
Fixed. Please check.

**Comment by AmandaBekhoj** [comment]
perfect, thanks!
