### ISSUE TITLE
Extra spaces in the text

### ISSUE THREAD

**Issue by mamont77** [mamont77/infrahouse#50]
Amanda,
Please fix if possible. I see a lot of spaces, where it should not be.
![client management brugercentreret it infrastruktur - google ch 01-05-2015 12 03 31](https://cloud.githubusercontent.com/assets/970967/5612045/71c10f16-94d7-11e4-977a-bc07c789fb39.png)
![losninger brugercentreret it infrastruktur - google chrome 01-05-2015 12 37 05](https://cloud.githubusercontent.com/assets/970967/5612063/aa2f879c-94d7-11e4-827e-caaf32a7ada0.png)

**Comment by AmandaBekhoj** [comment]
hm that is weird, it was not like that earlier

**Comment by AmandaBekhoj** [comment]
i don't know how to fix, when i go to edit, the text is correct with none of the spaces?? i do not know what to dooo?

**Comment by mamont77** [comment]
It seems the code has a lot of garbage.
![edit basic page client management brugercentreret it infrastru 01-05-2015 14 00 08](https://cloud.githubusercontent.com/assets/970967/5612803/4c02b4a8-94e3-11e4-851e-0d044d7f87d5.png)
It is WYSIWYG editor could add it.
Then Drupal's filter adds extra space.

We can use this buttons
![edit basic page client management brugercentreret it infrastru 01-05-2015 14 03 52](https://cloud.githubusercontent.com/assets/970967/5612829/c9a39e18-94e3-11e4-848e-295b9c933f46.png).
In this case, I do not see the extra tag. But I see that the spaces are replaced by the entity. I do not like it too.
![edit basic page client management brugercentreret it infrastru 01-05-2015 14 05 57](https://cloud.githubusercontent.com/assets/970967/5612862/0fed1278-94e4-11e4-98e6-07994d5f15e7.png)

Please wait. I'll try to fix it on the Drupal side.

**Comment by mamont77** [comment]
Amanda, please try the following sequence.
1. Select all
2. Remove format.
3. Save content.
http://www.infrahouse.com/da/client-management

![edit basic page client management brugercentreret it infrastru 01-05-2015 14 45 23](https://cloud.githubusercontent.com/assets/970967/5613229/9fee5044-94e9-11e4-83d9-db7732ecd8f5.png)

**Comment by AmandaBekhoj** [comment]
that helped! do i have to do it on all the pages??

**Comment by mamont77** [comment]
Yes. It is not urgent. Only when you see places like this.

**Comment by AmandaBekhoj** [comment]
okay, i does not look like there are any more pages with the same problem. but thanks for telling me the trick to fix it ;)

**Comment by mamont77** [comment]
In fact, the trick is, I deleted all the buttons that you can break the text. )) Leave only the most necessary. Show all screenshots in this issue.
You are welcome))

**Comment by AmandaBekhoj** [comment]
haha that is a perfect trick! less to be confused about :D :dancer:
