### ISSUE TITLE
alignment of boxes

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#51]
Hi Ruslan,

on the front page there are three boxes, and they are not aligned. you think you can fix? :)

![skaermbillede 2015-01-07 kl 12 20 40](https://cloud.githubusercontent.com/assets/8081414/5644823/1eaca26c-9668-11e4-89f2-47e1d85c4632.png)

**Comment by mamont77** [comment]
Okay. I will fix later today. :)

**Comment by mamont77** [comment]
Please check now.

**Comment by AmandaBekhoj** [comment]
perfect, much better :)
