### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#52]
Hi Ruslan

I need some help. 

I have posted a blog entity, and i need to link to a program download. but it seems like i cannot figure out how to do that.

I know i need to upload the program file to the website, but again, i do not know how. i will send you the two program files in an email, maybe you can do it on the english version of the blog entity, and then i can do it myself on the danish version? :)

the blog entity is called ' How to extract USMT/Windows Easy Transfer .MIG files'

you think you can help? :)

**Comment by mamont77** [comment]
This time I added the files manually via FTP.
Node was updated.
![hvordan udpakker man usmt windows easy transfer mig filer bru 01-13-2015 16 34 23](https://cloud.githubusercontent.com/assets/970967/5722119/22a5b898-9b42-11e4-9324-9bac9fd8f875.png)
If you plan to add these files often, I can add a field for this case.

**Comment by AmandaBekhoj** [comment]
i think i might be adding them often! could you add a field for it?

and thanks! :D

**Comment by mamont77** [comment]
Done.
I created a simple field.
![1](https://cloud.githubusercontent.com/assets/970967/5722341/102c8eba-9b44-11e4-889d-c629eb880349.png)
You can copy link's url and to use in content.
![2](https://cloud.githubusercontent.com/assets/970967/5722348/2a42ffd2-9b44-11e4-8ad2-a941f8d832b5.png)

**Comment by AmandaBekhoj** [comment]
you are a superstar, thanks!

**Comment by mamont77** [comment]
you too :-D
