### ISSUE TITLE
blog entities in english version

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#53]
There is something wrong with the blog entities menu - there is only one of the tags present?

![skaermbillede 2015-01-13 kl 14 06 08](https://cloud.githubusercontent.com/assets/8081414/5721267/c6638306-9b2f-11e4-96a1-83fc2c4eb3f7.png)

**Comment by mamont77** [comment]
Because 
![2](https://cloud.githubusercontent.com/assets/970967/5722194/d42c1382-9b42-11e4-99cf-f4e296944fa4.png)
But
![1](https://cloud.githubusercontent.com/assets/970967/5722197/d944d034-9b42-11e4-9567-770596a4d742.png)

Fixed here: http://www.infrahouse.com/en/admin/structure/taxonomy/tags

**Comment by AmandaBekhoj** [comment]
thanks :D
