### ISSUE TITLE
infrahouse.com does not work

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#54]
are you currently working on infrahouse.dk? it will not open the site :(

**Comment by AmandaBekhoj** [comment]
[insert state of panic]

**Comment by mamont77** [comment]
Amanda, 
I have always used this address infrahouse.com. NOT dk.

**Comment by mamont77** [comment]
I can write a ticket on https://www.dandomain.dk/kundecenter.html about infrahouse.dk if you want.

**Comment by AmandaBekhoj** [comment]
ah yes, that is a mistake. i did not even notice! sorry. but infrahouse.com did not work earlier, i was really weird.. but now it does..

we do not need at ticket for the infrahouse.dk, but thanks :)

**Comment by AmandaBekhoj** [comment]
i have this problem again. it occurs sometimes, that the website won't open? it seems really strange. and very annoying

**Comment by mamont77** [comment]
Site infrahouse.com works to me now.
In any case, the reason is not site, and hosting. Possible hardware replacement or maintenance work.
If this happens often, you can write a letter in support (https://www.dandomain.dk/kundecenter.html).
Or look for a new hosting.

I changed the title from "infrahouse.dk" does not work to "infrahouse.com does not work".

**Comment by mamont77** [comment]
if it doesn't work to you, please attach # of error or screen snap

**Comment by AmandaBekhoj** [comment]
hm, it happens to me all the time these days. and it still does not work for me. i will try and write dandomain an email

**Comment by AmandaBekhoj** [comment]
![skaermbillede 2015-01-26 kl 14 27 53](https://cloud.githubusercontent.com/assets/8081414/5900277/89b48c10-a567-11e4-9619-96e9369b8b1e.png)

**Comment by AmandaBekhoj** [comment]
it says it cannot find the server

**Comment by mamont77** [comment]
Amanda, can you try load the site using http://anonim.pro/ or other?

**Comment by AmandaBekhoj** [comment]
it works! looks like this 
![skaermbillede 2015-01-26 kl 14 32 37](https://cloud.githubusercontent.com/assets/8081414/5900346/3da92096-a568-11e4-9c19-49b6fae8a7d9.png)

**Comment by mamont77** [comment]
So site works. Problem on your side (((

**Comment by AmandaBekhoj** [comment]
okay, so i write to dandomain to find the error?

**Comment by mamont77** [comment]
No. Site works! I can check your computer using team viewer.

**Comment by AmandaBekhoj** [comment]
but it is not only me, my colleague cannot see the site either

on both safari and firefox

**Comment by AmandaBekhoj** [comment]
it says it cannot find the server? where did it hide?

**Comment by mamont77** [comment]
I'm writing in skype.
