### ISSUE TITLE
flag reflections on front page

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#55]
Hi Ruslan, 
I hope your son is feeling better?

do you think it is possible to have the flags be reflected, as the text is, on the front page?
![skaermbillede 2015-02-03 kl 13 04 04](https://cloud.githubusercontent.com/assets/8081414/6019896/ca24825c-aba5-11e4-874b-d25b9e04bc2e.png)

**Comment by mamont77** [comment]
Son is recovering. Thank you for caring.
I think it is possible in theory, but very difficult to implement. Take a few hours in advance and can not give guarantees.

**Comment by AmandaBekhoj** [comment]
okay, i will talk to christian about it

**Comment by AmandaBekhoj** [comment]
we will not do this :)
