### ISSUE TITLE
blog categories

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#56]
For some reason, the new job categories are not shown on in the left side menu?
both english and danish
![skaermbillede 2015-02-04 kl 16 36 57](https://cloud.githubusercontent.com/assets/8081414/6043911/19b2b22c-ac90-11e4-8c80-cfcb765e0a27.png)

![skaermbillede 2015-02-04 kl 16 36 12](https://cloud.githubusercontent.com/assets/8081414/6043913/1bc9a818-ac90-11e4-9f26-48d240af3df7.png)

**Comment by mamont77** [comment]
I made a few changes and I hope that it will work better.
If this happens, press "Select to rebuild the menu on submit" on http://www.infrahouse.com/da/admin/structure/taxonomy/tags/edit
but of course it should work automatically. I'll be watching it.

Fixed for the "OPERATING SYSTEM".

**Comment by AmandaBekhoj** [comment]
thanks :))
