### ISSUE TITLE
missing space

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#57]
there is missing a space between 'Submitted by' and 'Name' on the blog sites :)

like this:
![skaermbillede 2015-02-18 kl 13 48 18](https://cloud.githubusercontent.com/assets/8081414/6247464/1d746f28-b775-11e4-9b83-78a19059e531.png)

It is the same on all blog posts

**Comment by mamont77** [comment]
Fixed.

**Comment by AmandaBekhoj** [comment]
thanks!
