### ISSUE TITLE
social symbols

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#58]
Can we have Facebook and linkedin share buttons on out job pages for infrahouse?
that way, it is possible to share the job postings :)

**Comment by mamont77** [comment]
Hi.

Yes, we can. But i can't found  job pages on infrahouse.
Show me an example of a page.

Or maybe  you  meant salestribe?

**Comment by AmandaBekhoj** [comment]
nopes, i mean these :)
http://www.infrahouse.com/da/microsoft-infrastrukturkonsulent
http://www.infrahouse.com/da/intern-koordinator

i know they are normal pages, i am sorry!

**Comment by mamont77** [comment]
Ok.

Option 1:
We can add  "Facebook" + "linkedin" + "google" + "twitter" like on this page http://www.infrahouse.com/da/blog/author/itmc-soft/idm365-identity-and-access-management-finance-sector (float left in content).

Option 2:
I have got create temporary block on left sidebar:
![microsoft infrastrukturkonsulent brugercentreret it infrastruk 03-10-2015 16 39 40](https://cloud.githubusercontent.com/assets/970967/6577109/27188e9a-c744-11e4-95a7-d0de45263214.png)
(visible for admin only now).
I can do what would it look more beautiful.

What do you prefer?

**Comment by AmandaBekhoj** [comment]
hm, i think i prefer floating, like on the blog pages. then we can locate them like this?
![skaermbillede 2015-03-10 kl 16 14 57](https://cloud.githubusercontent.com/assets/8081414/6577809/b568f210-c740-11e4-9e58-ba1d4a3e2898.png)

**Comment by mamont77** [comment]
Ok. I can :-) In process.

**Comment by mamont77** [comment]
It's hard to be placed at the node title area. I placed in the body, as it works in the blog entity.
Please check.
![intern koordinator brugercentreret it infrastruktur - google c 03-10-2015 17 35 22](https://cloud.githubusercontent.com/assets/970967/6578350/52a91f36-c74c-11e4-84ef-0c3925b87faa.png)

**Comment by mamont77** [comment]
I can move "service-links" element to another area (after node title) using javascript if you want.

**Comment by AmandaBekhoj** [comment]
it looks good! thanks :)
