### ISSUE TITLE
A demo button on the IDM365 landing page 

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/infrahouse#59]
We need a button on the IDM365 landing page, that should lead to a demo site for the IDM365 system.. it should be on all of the three carousel slides :)
![skaermbillede 2015-03-11 kl 09 58 47](https://cloud.githubusercontent.com/assets/8081414/6593098/8d331268-c7d5-11e4-9e66-18e95e4dcd7b.png)

![skaermbillede 2015-03-11 kl 09 54 52](https://cloud.githubusercontent.com/assets/8081414/6593102/8f7fb634-c7d5-11e4-98d9-b9f18aa865df.png)

the link to the demo: http://demo.idm365.com 

does this make sense? :)

**Comment by mamont77** [comment]
Please test it.
![brugercentreret it infrastruktur - google chrome 03-12-2015 13 44 59](https://cloud.githubusercontent.com/assets/970967/6617131/14101aae-c8be-11e4-8b28-f79a6ad215a1.png)

**Comment by AmandaBekhoj** [comment]
it works, perfect! thanks :)

**Comment by AmandaBekhoj** [comment]
buut, you need to make it live :)

**Comment by mamont77** [comment]
What do you mean in last comment :)

**Comment by AmandaBekhoj** [comment]
i think right now only administrator can se it?

**Comment by AmandaBekhoj** [comment]
because when i am logged out, then i cannot see the button

**Comment by mamont77** [comment]
I forgot to do this for the English version.

And Caches cleared.
(http://www.infrahouse.com/en/admin/config/development/performance)

Try now.

**Comment by AmandaBekhoj** [comment]
works now :)
